# Generated by Django 6.0.5 on 2026-05-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='distinguished_name',
            field=models.TextField(help_text='Full DN from certificate subject', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='edipi',
            field=models.CharField(help_text='CAC identifier — DoD EDIPI (10-digit) or Ascendant AGID (e.g. TAG-000001)', max_length=20, unique=True),
        ),
    ]
