# Generated by Django 6.0.5 on 2026-06-06 20:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0002_hostcommand_argument_hint_hostcommand_takes_argument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_id', models.CharField(help_text='e.g. HV-004', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('both', 'Both')], max_length=10)),
                ('category', models.CharField(help_text='e.g. hyperv, storage, network', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('yaml_path', models.CharField(help_text='Relative path to YAML file', max_length=500)),
                ('autonomous', models.BooleanField(default=False, help_text='Whether this rule can take autonomous remediation action')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('testing', 'Testing')], default='active', max_length=10)),
                ('loaded_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rule_id'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('probable_cause', models.TextField()),
                ('detail', models.TextField(blank=True, help_text='Raw command output that triggered this finding')),
                ('recommendation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('remediated', 'Remediated'), ('escalated', 'Escalated'), ('dismissed', 'Dismissed')], default='open', max_length=15)),
                ('rule_version', models.CharField(help_text='Version of rule at time of finding', max_length=20)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='hosts.managedhost')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='diagnostics.diagnosticrule')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='RemediationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='The action that was taken', max_length=200)),
                ('command', models.TextField(blank=True, help_text='Command executed on the host')),
                ('output', models.TextField(blank=True, help_text='Command output / result')),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('skipped', 'Skipped')], max_length=10)),
                ('trigger', models.CharField(choices=[('autonomous', 'Autonomous'), ('approved', 'Operator Approved'), ('manual', 'Manual')], max_length=15)),
                ('rule_id', models.CharField(max_length=20)),
                ('rule_version', models.CharField(max_length=20)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_message', models.TextField(blank=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remediation_logs', to='diagnostics.diagnosticfinding')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='Null if autonomous', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remediation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
