# Generated by Django 6.0.5 on 2026-05-28 00:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('system_name', models.CharField(choices=[('servicenow', 'ServiceNow'), ('jira', 'Jira Service Management'), ('remedy', 'BMC Remedy'), ('custom', 'Custom')], max_length=20)),
                ('base_url', models.URLField()),
                ('auth_type', models.CharField(choices=[('oauth', 'OAuth 2.0'), ('apikey', 'API Key'), ('basic', 'Basic Auth')], max_length=10)),
                ('auth_config', models.TextField(help_text='Encrypted auth credentials (API key, OAuth tokens, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkLogExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_ticket_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('exported_content', models.TextField(help_text='The work log text that was sent')),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_log_exports', to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='tickets.ticketintegration')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_log_exports', to='sessions.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
