"""
apps/insights/models.py
Pattern analysis and actionable insight generation.
Insights are derived from command logs and session history.
"""

import uuid
from django.db import models


class Insight(models.Model):
    """
    A pattern or observation derived from command log analysis.
    Populated by Celery background tasks that analyze session history
    and surface recurring issues, root causes, and recommendations.
    """

    CATEGORY_CHOICES = [
        ('root_cause',      'Root Cause'),
        ('pattern',         'Recurring Pattern'),
        ('recommendation',  'Recommendation'),
        ('anomaly',         'Anomaly'),
        ('performance',     'Performance'),
    ]

    SEVERITY_CHOICES = [
        ('info',     'Informational'),
        ('low',      'Low'),
        ('medium',   'Medium'),
        ('high',     'High'),
        ('critical', 'Critical'),
    ]

    id               = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    host             = models.ForeignKey(
                           'hosts.ManagedHost',
                           on_delete=models.CASCADE,
                           related_name='insights',
                           null=True,
                           blank=True,
                           help_text="Null means this insight applies globally across all hosts"
                       )
    category         = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    severity         = models.CharField(max_length=10, choices=SEVERITY_CHOICES, default='info')
    title            = models.CharField(max_length=300)
    description      = models.TextField()
    recommendation   = models.TextField(
                           blank=True,
                           help_text="Actionable steps to address this insight"
                       )
    occurrence_count = models.PositiveIntegerField(default=1)
    first_seen       = models.DateTimeField(auto_now_add=True)
    last_seen        = models.DateTimeField(auto_now=True)
    is_resolved      = models.BooleanField(default=False)
    resolved_at      = models.DateTimeField(null=True, blank=True)
    resolved_by      = models.ForeignKey(
                           'accounts.User',
                           on_delete=models.SET_NULL,
                           null=True,
                           blank=True,
                           related_name='resolved_insights'
                       )
    supporting_log_ids = models.JSONField(
                             default=list,
                             help_text="List of CommandLog UUIDs that support this insight"
                         )

    class Meta:
        ordering = ['-last_seen', '-severity']

    def __str__(self):
        host_str = self.host.hostname if self.host else 'Global'
        return f"[{self.get_severity_display()}] {self.title} ({host_str})"

    def increment(self):
        """Call when this pattern is observed again."""
        self.occurrence_count += 1
        self.save(update_fields=['occurrence_count', 'last_seen'])


class UserPerformanceSnapshot(models.Model):
    """
    Periodic snapshots of user activity metrics for leadership reporting.
    Generated by a Celery task on a configurable schedule (e.g. weekly).
    """

    id           = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user         = models.ForeignKey(
                       'accounts.User',
                       on_delete=models.CASCADE,
                       related_name='performance_snapshots'
                   )
    period_start = models.DateTimeField()
    period_end   = models.DateTimeField()

    # Activity metrics
    session_count        = models.PositiveIntegerField(default=0)
    command_count        = models.PositiveIntegerField(default=0)
    unique_hosts_touched = models.PositiveIntegerField(default=0)
    avg_session_duration = models.DurationField(null=True, blank=True)
    tickets_referenced   = models.PositiveIntegerField(default=0)

    # Quality metrics
    work_logs_exported   = models.PositiveIntegerField(default=0)
    notes_added          = models.PositiveIntegerField(
                               default=0,
                               help_text="Sessions where the technician added notes"
                           )

    # Raw data for deeper analysis
    command_breakdown    = models.JSONField(
                               default=dict,
                               help_text="Dict of command_name -> count for this period"
                           )
    host_breakdown       = models.JSONField(
                               default=dict,
                               help_text="Dict of hostname -> session count for this period"
                           )

    generated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-period_end']
        unique_together = [['user', 'period_start', 'period_end']]

    def __str__(self):
        return f"{self.user} — {self.period_start:%Y-%m-%d} to {self.period_end:%Y-%m-%d}"
