# Generated by Django 6.0.5 on 2026-05-28 00:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('system', 'System Info'), ('services', 'Service Management'), ('logs', 'Log Access'), ('network', 'Network'), ('storage', 'Storage'), ('cluster', 'Cluster'), ('backup', 'Backup'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('platform', models.CharField(choices=[('all', 'All Platforms'), ('windows', 'Windows Only'), ('linux', 'Linux Only')], default='all', max_length=10)),
                ('takes_argument', models.BooleanField(default=False, help_text='Whether this command accepts an argument (e.g. service_status <name>)')),
                ('argument_hint', models.CharField(blank=True, help_text="Hint shown in the UI for the argument (e.g. 'service name')", max_length=100)),
                ('requires_elevation', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'command_name'],
            },
        ),
    ]
