# Generated by Django 6.0.5 on 2026-05-28 00:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_ref', models.CharField(blank=True, help_text='Optional ticket number this session is associated with', max_length=100)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('termination_reason', models.CharField(blank=True, choices=[('user_closed', 'Closed by user'), ('timeout', 'Session timeout'), ('disconnected', 'Client disconnected'), ('error', 'Error')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Freeform notes the technician can add during or after the session')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='hosts.managedhost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_name', models.CharField(max_length=100)),
                ('command_args', models.TextField(blank=True)),
                ('result_output', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_logs', to='hosts.managedhost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_logs', to='radmin_sessions.session')),
            ],
            options={
                'ordering': ['executed_at'],
            },
        ),
    ]
