# Generated by Django 6.0.5 on 2026-05-28 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedHost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('os_type', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('macos', 'macOS')], default='windows', max_length=20)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('development', 'Development'), ('lab', 'Lab')], default='production', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_hosts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='HostCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('system', 'System Info'), ('services', 'Service Management'), ('logs', 'Log Access'), ('network', 'Network'), ('storage', 'Storage'), ('cluster', 'Cluster'), ('backup', 'Backup'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('requires_elevation', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='hosts.managedhost')),
            ],
            options={
                'ordering': ['category', 'command_name'],
                'unique_together': {('host', 'command_name')},
            },
        ),
    ]
