# Generated by Django 6.0.5 on 2026-05-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostcommand',
            name='argument_hint',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hostcommand',
            name='takes_argument',
            field=models.BooleanField(default=False),
        ),
    ]
