# Generated by Django 6.0.5 on 2026-05-28 00:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('root_cause', 'Root Cause'), ('pattern', 'Recurring Pattern'), ('recommendation', 'Recommendation'), ('anomaly', 'Anomaly'), ('performance', 'Performance')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True, help_text='Actionable steps to address this insight')),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('supporting_log_ids', models.JSONField(default=list, help_text='List of CommandLog UUIDs that support this insight')),
                ('host', models.ForeignKey(blank=True, help_text='Null means this insight applies globally across all hosts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='hosts.managedhost')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen', '-severity'],
            },
        ),
        migrations.CreateModel(
            name='UserPerformanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('session_count', models.PositiveIntegerField(default=0)),
                ('command_count', models.PositiveIntegerField(default=0)),
                ('unique_hosts_touched', models.PositiveIntegerField(default=0)),
                ('avg_session_duration', models.DurationField(blank=True, null=True)),
                ('tickets_referenced', models.PositiveIntegerField(default=0)),
                ('work_logs_exported', models.PositiveIntegerField(default=0)),
                ('notes_added', models.PositiveIntegerField(default=0, help_text='Sessions where the technician added notes')),
                ('command_breakdown', models.JSONField(default=dict, help_text='Dict of command_name -> count for this period')),
                ('host_breakdown', models.JSONField(default=dict, help_text='Dict of hostname -> session count for this period')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end'],
                'unique_together': {('user', 'period_start', 'period_end')},
            },
        ),
    ]
